# Root Netlify config referencing app in ./project
# Fixes build path so Netlify runs inside project/ where package.json lives.

[build]
  base = "project"          # Change working directory before running command
  publish = "dist"          # Because base moves us into project/, publish path is relative to that
  command = "npm run build"  # Uses scripts from project/package.json

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Environment (optional examples)
#[[build.environment]]
#  NODE_VERSION = "18"

# API proxy must precede SPA fallbacks
[[redirects]]
  from = "/api/*"
  to = "https://omraneva.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "netlify" }

# Mobile variant SPA fallback
[[redirects]]
  from = "/m/*"
  to = "/m/index.html"
  status = 200

# Desktop SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/"                   # Run for all requests (mobile redirect logic checks UA & path)
  function = "mobile-redirect"  # File: project/netlify/edge-functions/mobile-redirect.js

# (Optional) Future: Add function for prefs, A/B, etc.
