# Root Netlify config referencing app in ./project
# Fixes build path so Netlify runs inside project/ where package.json lives.

[build]
  base = "project"          # Change working directory before running command
  publish = "dist"          # Because base moves us into project/, publish path is relative to that
  command = "npm run build"  # Uses scripts from project/package.json

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--no-audit --no-fund"

## Edge Functions configuration
## Netlify requires [[edge_functions]] array entries. Each object maps a path to a function.
[[edge_functions]]
  path = "/*"        # Run for all routes (function itself filters assets & /api)
  function = "mobile-redirect"

# Environment (optional examples)
#[[build.environment]]
#  NODE_VERSION = "18"

# API proxy must precede SPA fallbacks
[[redirects]]
  from = "/api/*"
  to = "https://omraneva.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "netlify" }

# Mobile variant SPA fallback
[[redirects]]
  from = "/m/*"
  to = "/m/index.html"
  status = 200

# Desktop SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## Edge function routing moved to per-file export config (edge-functions/mobile-redirect.js)
## Keeping only the directory declaration above to avoid duplicate key parsing error.

# (Optional) Future: Add function for prefs, A/B, etc.
