# Netlify configuration for unified web + mobile (/m) build
# Single Vite multi-page build outputs:
#   dist/index.html (desktop)
#   dist/m/index.html (mobile variant)

[build]
  publish = "dist"
  command = "npm run build" # Multi-page build already emits /m entry

# Edge Function handles UA detection. See netlify/edge-functions/mobile-redirect.js

## API proxy to Render backend (must come before SPA fallbacks)
[[redirects]]
  from = "/api/*"
  to = "https://omraneva.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "netlify" }

[[redirects]]
  from = "/m/*"
  to = "/m/index.html"
  status = 200

# SPA fallback for web
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


# Edge functions directory (auto-detected by Netlify CLI if using default path)
[edge_functions]
  directory = "netlify/edge-functions"

